//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.17 at 01:32:55 PM MSD 
//

@javax.xml.bind.annotation.XmlSchema(
namespace = "http://www.topografix.com/GPX/1/1", 
        xmlns={
		@javax.xml.bind.annotation.XmlNs(namespaceURI=consts.gpxx, prefix="gpxx" ),
        @javax.xml.bind.annotation.XmlNs(namespaceURI=consts.gpxtpx,prefix="gpxtpx" ),
        @javax.xml.bind.annotation.XmlNs(namespaceURI=consts.gpxtrx,prefix="gpxtrx" )
//        @javax.xml.bind.annotation.XmlNs(namespaceURI=com.sun.xml.internal.bind.v2.WellKnownNamespace.XML_SCHEMA_INSTANCE ,prefix="xsi" )
	},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.maptrack.client.gpx;

import com.maptrack.client.entrys.consts;

